In [1]:
import sys
sys.path.append('../scripts/')
from mcl_edit import *

In [2]:
def trial():
    time_interval = 0.1
    world = World(100, time_interval, debug = True)
    
    m = Map()
    straight = Agent(2.0,0)
    initial_pose_1 = np.array([0,0,0]).T
    #initial_pose_3 = np.array([-200,-200,math.pi]).T
    #initial_pose_4 = np.array([200,-200,math.pi / 2]).T
    m.append_landmark(Landmark(initial_pose_1, agent = straight))
    #m.append_landmark(Landmark(initial_pose_3, agent = straight))
    #m.append_landmark(Landmark(initial_pose_4, agent = straight))
    world.append(m)    

    initial_pose_2 = np.array([-200,-200,math.pi / 2 ]).T
    estimator2 = Mcl(m,initial_pose_2,100)
    b = EstimationAgent(time_interval, 1,0,estimator2)
    r_2 = Robot(initial_pose_2 , sensor = Camera(m),agent = b, color = "blue")
    world.append(r_2)
    #r_3 = IdealRobot(initial_pose_2, sensor=IdealCamera(m), agent=straight, color="red") 
    #world.append(r_3)
    world.draw()
    
trial()

[ -28.38361932 -396.2575819     1.60198936]
[ -33.88218429 -412.55955419    1.6693479 ]
[ -36.71664805 -391.29821785    1.64145267]
[ -37.9134146  -404.10905704    1.66574941]
[ -39.9368661  -394.65018897    1.61779413]
[  -8.67767958 -402.64055876    1.55500767]
[   0.87673804 -394.70348681    1.52201076]
[   0.57465147 -386.50784008    1.50290192]
[ -39.86476817 -408.79656334    1.62877016]
[ -57.33091629 -411.51441784    1.70987889]
[ -76.45728047 -405.89232612    1.72256322]
[ -85.57563667 -420.06008204    1.75327669]
[ -86.54633303 -399.926511      1.75744736]
[ -86.00518163 -427.56303633    1.77099242]
[ -90.88319984 -409.92868887    1.73941728]
[ -97.64351508 -407.93356161    1.77237296]
[-107.19846107 -395.61094086    1.76832913]
[-103.52980609 -405.26542546    1.73591741]
[-102.94384148 -418.1455197     1.77342358]
[-112.6837542  -392.1287245     1.74614208]
[-124.52100207 -399.88551691    1.75620433]
[-131.75289032 -408.37929518    1.77820391]
[-137.27545998 -387.77512727    

In [ ]:
    def shift_transition(self, nu, omega, time):
        t0 = self.pose[2]
        if math.fabs(omega) < 1e-10:
            return self.pose + np.array( [nu*math.cos(t0)+2.0,
                                     nu*math.sin(t0),
                                     omega ] ) / math.sqrt((nu*math.cos(t0)+2.0)**2 +(nu*math.sin(t0))**2) * math.sqrt((nu*math.cos(t0))**2 +(nu*math.sin(t0))**2) * time
        else:
            return self.pose + np.array( [nu/omega*(math.sin(t0 + omega*time)- math.sin(t0))+2.0,nu/omega*(-math.cos(t0 + omega*time) + math.cos(t0)),                                    omega*time ] )
        / math.sqrt((nu/omega*(math.sin(t0 + omega*time) - math.sin(t0))+2.0)**2 + (nu/omega*(-math.cos(t0 + omega*time) + math.cos(t0))**2 ))  * math.sqrt((nu/omega*(math.sin(t0 + omega*time) - math.sin(t0)))**2 + (nu/omega*(-math.cos(t0 + omega*time) + math.cos(t0))**2 ))

In [ ]:
           print(self.pose + np.array([obs[0][0][0] * math.cos(obs[0][0][1]), obs[0][0][0] * math.sin(obs[0][0][1]),0]))